- Pages (Check)
- Number of deaths (Check)
    - ERROR
- Clean of fields
- QC detainee $ ocrurrences 
- Compare to 500

In [2]:
import polars as pl
import altair as alt
from pathlib import Path
import json

In [4]:
root = Path('..')
parquet_path = root / 'data/jails-data/final files/output/jails_person_records.parquet'
complete_df_path = root / 'data/jails-data/final files/output/jails_pdfs_full.parquet'
df = pl.read_parquet(parquet_path)
df_complete = pl.read_parquet(complete_df_path)
df.head()

shape: (5, 5)
┌─────────────────────────┬────────────────────┬───────────┬───────────────┬───────────────────┐
│ Report ID               ┆ Name               ┆ DOB       ┆ Date_Confined ┆ Arresting_Charge  │
│ ---                     ┆ ---                ┆ ---       ┆ ---           ┆ ---               │
│ str                     ┆ str                ┆ str       ┆ str           ┆ str               │
╞═════════════════════════╪════════════════════╪═══════════╪═══════════════╪═══════════════════╡
│ Mateos, Gustavo 1-14_p1 ┆ null               ┆ null      ┆ null          ┆ posse es          │
│ Mateos, Gustavo 1-14_p1 ┆ _ Mateos, Gustavo  ┆ 1/22/1995 ┆ null          ┆ "01/24/2020       │
│ Searle, Robert 1-21_p1  ┆ null               ┆ null      ┆ null          ┆ | METHAMPHETAMINE │
│ Searle, Robert 1-21_p1  ┆ | Searle, Robert | ┆ null      ┆ null          ┆ : 11/14/1981      │
│ Sutton, Micah 1-6_p1    ┆ null               ┆ null      ┆ 01/06/2021    ┆ 98/08/1983        │
└─────────────────────────┴────────────────────┴───────────┴───────────────┴───────────────────┘

In [13]:
type(df_complete['Table Contents'])

polars.series.series.Series

In [18]:
type(df_complete[3500]['Table Contents'])

polars.series.series.Series

In [14]:
type(df_complete[2993]['Table Contents'])

polars.series.series.Series

In [24]:
print(df_complete[3500]['Table Contents'][0].to_list())

['Antonio D Hall', '9/20/1991', '1/10/2024', 'Burglary']

In [12]:
print(df_complete[2993]['Table Contents'])

shape: (1,)
Series: 'Table Contents' [list[str]]
[
	["Ordonez, Robert F.", "08/12/1981", … "Crim.Damage Govt.Property"]
]

In [5]:
df_cleaned = df.with_columns(
    pl.col("Name")
    .str.replace_all(r"[;|_\-!~\"“”]", "")  # Remove ; | _ - ! ~ " “ ”
    .str.strip_chars()
    .alias("Cleaned Name")
)

In [6]:
df_cleaned

shape: (14_044, 6)
┌───────────────────┬───────────┬────────────┬───────────────┬──────────────────┬──────────────────┐
│ Report ID         ┆ Name      ┆ DOB        ┆ Date_Confined ┆ Arresting_Charge ┆ Cleaned Name     │
│ ---               ┆ ---       ┆ ---        ┆ ---           ┆ ---              ┆ ---              │
│ str               ┆ str       ┆ str        ┆ str           ┆ str              ┆ str              │
╞═══════════════════╪═══════════╪════════════╪═══════════════╪══════════════════╪══════════════════╡
│ Mateos, Gustavo   ┆ null      ┆ null       ┆ null          ┆ posse es         ┆ null             │
│ 1-14_p1           ┆           ┆            ┆               ┆                  ┆                  │
│ Mateos, Gustavo   ┆ _ Mateos, ┆ 1/22/1995  ┆ null          ┆ "01/24/2020      ┆ Mateos, Gustavo  │
│ 1-14_p1           ┆ Gustavo   ┆            ┆               ┆                  ┆                  │
│ Searle, Robert    ┆ null      ┆ null       ┆ null          ┆ |                ┆ null             │
│ 1-21_p1           ┆           ┆            ┆               ┆ METHAMPHETAMINE  ┆                  │
│ Searle, Robert    ┆ | Searle, ┆ null       ┆ null          ┆ : 11/14/1981     ┆ Searle, Robert   │
│ 1-21_p1           ┆ Robert |  ┆            ┆               ┆                  ┆                  │
│ Sutton, Micah     ┆ null      ┆ null       ┆ 01/06/2021    ┆ 98/08/1983       ┆ null             │
│ 1-6_p1            ┆           ┆            ┆               ┆                  ┆                  │
│ …                 ┆ …         ┆ …          ┆ …             ┆ …                ┆ …                │
│ UO - FOIA January ┆ null      ┆ null       ┆ null          ┆ we Prey, x¢      ┆ null             │
│ 2023_p608         ┆           ┆            ┆               ┆                  ┆                  │
│ UO - FOIA January ┆ ‘Aiyders  ┆ null       ┆ null          ┆ ‘t (OABG991"     ┆ ‘Aiyders         │
│ 2023_p608         ┆           ┆            ┆               ┆                  ┆                  │
│ UO - FOIA January ┆ Beasley,  ┆ 06/24/1994 ┆ 08/01/2022    ┆ Agg Batt/Corr    ┆ Beasley, Shiloe  │
│ 2023_p609         ┆ Shiloe    ┆            ┆               ┆ Emp/Cnt Blood,   ┆                  │
│ UO - FOIA January ┆ Agg Batt  ┆ null       ┆ null          ┆ null             ┆ Agg Batt         │
│ 2023_p609         ┆           ┆            ┆               ┆                  ┆                  │
│ UO - FOIA January ┆ null      ┆ 07/16/1982 ┆ 01/31/2023    ┆ WADDELL, DALLAS  ┆ null             │
│ 2023_p615         ┆           ┆            ┆               ┆                  ┆                  │
└───────────────────┴───────────┴────────────┴───────────────┴──────────────────┴──────────────────┘

In [7]:
df_complete.columns

['Deceased Name',
 'Deceased Cause',
 'Deceased Date and Time',
 'Deceased on Suicide Watch',
 'Deceased Reporter',
 'Deceased Examined by Physician',
 'Deceased Signs of Illness',
 'Facility Name',
 'Facility Type',
 'RD Number',
 'Phone Number',
 'Address',
 'Date',
 'Time of Day',
 'AM or PM',
 'Occurrence',
 'Table Contents',
 'Injuries?',
 'Resulting Death?',
 'process',
 'Report ID',
 'OCR_Confidence',
 'OCR_Word_Count',
 'OCR_Text_Detected',
 'Cook County?']

In [7]:
# merge with complet df to have the whol table of contents per pdf
df_merged = df_cleaned.join(
    df_complete.select(['Report ID', 'Table Contents']),
    on='Report ID',
    how='left'
)

In [ ]:
df_merged

In [ ]:
df_cleaned = df.with_columns(
    pl.col("Name")
    .str.replace_all(r"[;|_\-!~\"“”]", "")  # Remove ; | _ - ! ~ " “ ”
    .str.strip_chars()
    .alias("Cleaned Name")
)

name_counts = (
    df_cleaned
    .filter(
        pl.col("Cleaned Name").is_not_null()
    )
    .group_by("Cleaned Name")
    .len()
    .sort("len", descending=True)
    .head(50)
    .to_pandas()
)

# Bar chart of top 50 names with custom color
alt.Chart(name_counts).mark_bar(color='#E0AC3BA6').encode(
    x=alt.X('len:Q', title='Frequency'),
    y=alt.Y('Cleaned Name:N', sort='-x', title='Name'),
    tooltip=['Cleaned Name', 'len']
).properties(
    width=600,
    height=800,
    title='Top 50 Most Frequent Names'
)

alt.Chart(...)

# This file seems to have a different format

Lets open the data we are sure to have

In [4]:
#And all the database:
root = Path('..')
parquet_path = root / 'data/jails-data/output/jails_pdfs.parquet'
df = pl.read_parquet(parquet_path)
list(df['Facility Name'][0:10])

['-acility Name: McHenry County Adult Correctional Facility\n',
 "‘acility Name: Kane County Sheriff's Office\n",
 'Fax: (217) 558-4004\n‘acility Name: \\ tei So ( ae ( She cA Ofce\n',
 '‘acility Name: /¥lATTHSOns = otice = bn FAPAMEAT\nTT eee Py ml a ei fF gt Mm Ahh sn\n',
 '-acility Name: Lake County Adult Corrections\n',
 '‘acility Name: Williamson County Jail\n',
 '-acility Name: Lake County Jail\n',
 'Facility Name: Lake County Jail\n',
 'Fax: (217) 522-3906\n-acility Name: McLean County Jail\n',
 '‘acility Name: Macoupin County Sheriff\n']

In [5]:
def clean_facility_name(df):
    """Clean facility names using Polars expressions"""
    return df.with_columns(
        pl.col('Facility Name')
        # First, clean OCR artifacts
        .str.replace_all(r'\\n|\\\\|\\/', ' ')  # Remove \n, \\, \/
        .str.replace_all(r'\n', ' ')  # Remove actual newlines
        .str.replace_all(r'[\\\/]+', ' ')  # Clean slashes
        .str.replace_all(r'\s+', ' ')  # Multiple spaces to single
        .str.strip_chars()  # Trim whitespace
        # Extract facility name after any variation of "Name:"
        .str.extract(r'cility Name:\s*(.+)', 1)
        # Additional cleanup of extracted names
        .str.replace_all(r'[^a-zA-Z\s\'-]', ' ')  # Keep only letters, spaces, apostrophes, hyphens
        .str.replace_all(r'\s+', ' ')  # Clean multiple spaces again
        .str.strip_chars()  # Final trim
        .alias('Cleaned Facility Name')
    )

# Apply the cleaning
df_cleaned = clean_facility_name(df)
df_cleaned['Facility Name', 'Cleaned Facility Name']

shape: (27_333, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ Facility Name                   ┆ Cleaned Facility Name           │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ -acility Name: McHenry County … ┆ McHenry County Adult Correctio… │
│ ‘acility Name: Kane County She… ┆ Kane County Sheriff's Office    │
│ Fax: (217) 558-4004             ┆ tei So ae She cA Ofce           │
│ ‘acility N…                     ┆                                 │
│ ‘acility Name: /¥lATTHSOns = o… ┆ lATTHSOns otice bn FAPAMEAT TT… │
│ -acility Name: Lake County Adu… ┆ Lake County Adult Corrections   │
│ …                               ┆ …                               │
│ SANs (att) Vee VI ——es-         ┆ null                            │
│ ‘acili…                         ┆                                 │
│ Facility Name: Lake County She… ┆ Lake County Sheriff's Office    │
│ -acility Name: Lake County Jai… ┆ Lake County Jail                │
│ Facility Name: Lake County Adu… ┆ Lake County Adult Correctional… │
│ SANs (att) Vee VI ——es-         ┆ null                            │
│ ‘acili…                         ┆                                 │
└─────────────────────────────────┴─────────────────────────────────┘

In [7]:
#Cleanning the date
list(df_cleaned['Date'][:10])

['Date of Occurrence: 01/09/2021\n',
 'Date of Occurrence: 01/27/2021\n',
 'aAqaaress. eet o~ SF Never\nPate af Praacemmamane f—) 7 + ed } fs 9 ng\n',
 'Date of Occurrence: i/ (Z]2 ( Tir\n',
 'Date of Occurrence: 01/15/2021\n',
 'Date of Occurrence: 01/14/2021\n',
 'Date of Occurrence: 01/19/2021\n',
 'Date of Occurrence: 01/13/2021\n',
 'AGaress. 14 West STORE SUCCL\nStreet\nRiwten af Manairrramnna: (111/12£/9N%1 ~\n',
 'Date of Occurrence: 01/26/2021 T\n']

In [10]:
def clean_date_occurrence(df):
    return df.with_columns(
        pl.col("Date")
          # OCR cleanup (keep forward slashes)
          .str.replace_all(r"\\n|\\\\", " ")
          .str.replace_all(r"\n", " ")
          .str.replace_all(r"\s+", " ")
          .str.strip_chars()
          # Extract the MM/DD/YYYY text
          .str.extract(r"Date of Occurrence:\s*([0-9]{1,2}/[0-9]{1,2}/(20[0-9]{2}))", 1)
          # Parse & re‐format to zero‐padded MM/DD/YYYY
          .str.strptime(pl.Date, "%m/%d/%Y", strict=False)
          .alias("temp_date")
    ).with_columns(
        # Only keep dates between 2000 and 2025, otherwise set to null
        pl.when(pl.col("temp_date").dt.year().is_between(2000, 2025))
        .then(pl.col("temp_date").dt.strftime("%m/%d/%Y"))
        .otherwise(None)
        .alias("Cleaned Date")
    ).drop("temp_date")

df_cleaned = clean_date_occurrence(df_cleaned)
df_cleaned.select(["Date","Cleaned Date"]).head(10)

shape: (10, 2)
┌─────────────────────────────────┬──────────────┐
│ Date                            ┆ Cleaned Date │
│ ---                             ┆ ---          │
│ str                             ┆ str          │
╞═════════════════════════════════╪══════════════╡
│ Date of Occurrence: 01/09/2021… ┆ 01/09/2021   │
│ Date of Occurrence: 01/27/2021… ┆ 01/27/2021   │
│ aAqaaress. eet o~ SF Never      ┆ null         │
│ Pat…                            ┆              │
│ Date of Occurrence: i/ (Z]2 ( … ┆ null         │
│ Date of Occurrence: 01/15/2021… ┆ 01/15/2021   │
│ Date of Occurrence: 01/14/2021… ┆ 01/14/2021   │
│ Date of Occurrence: 01/19/2021… ┆ 01/19/2021   │
│ Date of Occurrence: 01/13/2021… ┆ 01/13/2021   │
│ AGaress. 14 West STORE SUCCL    ┆ null         │
│ S…                              ┆              │
│ Date of Occurrence: 01/26/2021… ┆ 01/26/2021   │
└─────────────────────────────────┴──────────────┘

In [18]:
excel_path = root / 'data/jails-data/Initial 500 restraint chairs database.xlsx'
df_ex = pl.read_excel(excel_path, sheet_name='Chairs 19-22')
#df_ex.head()

Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 20, falling back to string

In [17]:
df_ex.filter(pl.col("PDF name").str.contains("Binder"))

shape: (24, 21)
┌────────────┬─────────────┬─────────────┬────────┬───┬─────────────┬────────┬─────────────┬───────┐
│ PDF folder ┆ PDF name    ┆ Date        ┆ R.D.   ┆ … ┆ Injuries?   ┆ Death? ┆ Reported by ┆ Notes │
│ ---        ┆ ---         ┆ received    ┆ Number ┆   ┆ ---         ┆ ---    ┆ ---         ┆ ---   │
│ str        ┆ str         ┆ ---         ┆ ---    ┆   ┆ str         ┆ str    ┆ str         ┆ str   │
│            ┆             ┆ date        ┆ str    ┆   ┆             ┆        ┆             ┆       │
╞════════════╪═════════════╪═════════════╪════════╪═══╪═════════════╪════════╪═════════════╪═══════╡
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-14  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-22  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-15  ┆ null   ┆ … ┆ No          ┆ null   ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-22  ┆ null   ┆ … ┆ Corbett-rig ┆ null   ┆ null        ┆ null  │
│            ┆             ┆             ┆        ┆   ┆ ht arm      ┆        ┆             ┆       │
│            ┆             ┆             ┆        ┆   ┆ scrape      ┆        ┆             ┆       │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-23  ┆ null   ┆ … ┆ No          ┆ null   ┆ null        ┆ null  │
│ …          ┆ …           ┆ …           ┆ …      ┆ … ┆ …           ┆ …      ┆ …           ┆ …     │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-28  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-07-02  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-23  ┆ null   ┆ … ┆ Head wound  ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-28  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
│ 2021_06    ┆ Binder1.pdf ┆ 2021-06-30  ┆ null   ┆ … ┆ No          ┆ No     ┆ null        ┆ null  │
└────────────┴─────────────┴─────────────┴────────┴───┴─────────────┴────────┴─────────────┴───────┘

In [19]:
df_cleaned

shape: (27_333, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Deceased  ┆ Deceased  ┆ Deceased  ┆ Deceased  ┆ … ┆ OCR_Text_ ┆ Cook      ┆ Cleaned   ┆ Cleaned  │
│ Cause,    ┆ on        ┆ Reporter  ┆ Examined  ┆   ┆ Detected  ┆ County?   ┆ Facility  ┆ Date     │
│ Date, and ┆ Suicide   ┆ ---       ┆ by        ┆   ┆ ---       ┆ ---       ┆ Name      ┆ ---      │
│ Time      ┆ Watch     ┆ str       ┆ Physician ┆   ┆ bool      ┆ str       ┆ ---       ┆ str      │
│ ---       ┆ ---       ┆           ┆ ---       ┆   ┆           ┆           ┆ str       ┆          │
│ str       ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ McHenry   ┆ 01/09/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Adult Cor ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ rectio…   ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Kane      ┆ 01/27/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Sheriff's ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Office    ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ tei So ae ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ She cA    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Ofce      ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ lATTHSOns ┆ null     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ otice bn  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ FAPAMEAT  ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ TT…       ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Lake      ┆ 01/15/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Adult Cor ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ rections  ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ null      ┆ null     │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Lake      ┆ 01/31/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 23       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Sheriff's ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Office    ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Lake      ┆ 01/31/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 23       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Jail      ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Lake      ┆ 01/31/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 23       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Adult Cor ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ rectional ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ …         ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ null      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
# Analysis with the excel Finding Binder pdf
df_cleaned.filter(pl.col("Report ID").str.contains("Binder"))

shape: (430, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Deceased  ┆ Deceased  ┆ Deceased  ┆ Deceased  ┆ … ┆ OCR_Text_ ┆ Cook      ┆ Cleaned   ┆ Cleaned  │
│ Cause,    ┆ on        ┆ Reporter  ┆ Examined  ┆   ┆ Detected  ┆ County?   ┆ Facility  ┆ Date     │
│ Date, and ┆ Suicide   ┆ ---       ┆ by        ┆   ┆ ---       ┆ ---       ┆ Name      ┆ ---      │
│ Time      ┆ Watch     ┆ str       ┆ Physician ┆   ┆ bool      ┆ str       ┆ ---       ┆ str      │
│ ---       ┆ ---       ┆           ┆ ---       ┆   ┆           ┆           ┆ str       ┆          │
│ str       ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Lake      ┆ 06/30/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Jail      ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ Cook      ┆ Cook      ┆ 06/09/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆ County    ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Departmen ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ t Of      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Corr…     ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ Cook      ┆ Cook      ┆ 06/29/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆ County    ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Departmen ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ t Of      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Corr…     ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Iroquois  ┆ 06/23/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 24       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Jail      ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ null      ┆ null     │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Madison   ┆ 06/04/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Sheriff's ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Offic…    ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Madison   ┆ 06/15/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Sheriff's ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Offic…    ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ Cook      ┆ Cook      ┆ 06/24/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆ County    ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Departmen ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ t Of      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Corr…     ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ Cook      ┆ Cook      ┆ 06/17/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆ County    ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Departmen ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ t Of      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Corr…     ┆          │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ true      ┆ null      ┆ Peoria    ┆ 06/11/20 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ County    ┆ 21       │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Sheriff's ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ Office    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘