- Pages (Check)
- Number of deaths (Check)
    - ERROR
- Clean of fields
- QC detainee $ ocrurrences 
- Compare to 500

In [2]:
import polars as pl
import altair as alt
from pathlib import Path
import json

In [3]:
root = Path('..')
parquet_path = root / 'data/jails-data/output/jails_pdfs_500.parquet'
df = pl.read_parquet(parquet_path)
df.head()

shape: (5, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Deceased  ┆ Deceased  ┆ Deceased  ┆ Deceased  ┆ … ┆ OCR_Confi ┆ OCR_Word_ ┆ OCR_Text_ ┆ Cook     │
│ Cause,    ┆ on        ┆ Reporter  ┆ Examined  ┆   ┆ dence     ┆ Count     ┆ Detected  ┆ County?  │
│ Date, and ┆ Suicide   ┆ ---       ┆ by        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ Time      ┆ Watch     ┆ str       ┆ Physician ┆   ┆ f64       ┆ i64       ┆ bool      ┆ str      │
│ ---       ┆ ---       ┆           ┆ ---       ┆   ┆           ┆           ┆           ┆          │
│ str       ┆ str       ┆           ┆ str       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ 81.92517  ┆ 294       ┆ true      ┆ null     │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ 89.217687 ┆ 294       ┆ true      ┆ Cook     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ County   │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ 87.556314 ┆ 293       ┆ true      ┆ Cook     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ County   │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ 87.513793 ┆ 290       ┆ true      ┆ Cook     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ County   │
│ N/A       ┆ N/A       ┆ N/A       ┆ N/A       ┆ … ┆ 87.691318 ┆ 311       ┆ true      ┆ null     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# This file seems to have a different format

Lets open the data we are sure to have

In [5]:
excel_path = root / 'data/jails-data/Initial 500 restraint chairs database.xlsx'
df = pl.read_excel(excel_path, sheet_name='Chairs 19-22')
df.head()

Could not determine dtype for column 3, falling back to string
Could not determine dtype for column 20, falling back to string

shape: (5, 21)
┌────────────┬──────────────┬──────────────┬────────┬───┬───────────┬────────┬─────────────┬───────┐
│ PDF folder ┆ PDF name     ┆ Date         ┆ R.D.   ┆ … ┆ Injuries? ┆ Death? ┆ Reported by ┆ Notes │
│ ---        ┆ ---          ┆ received     ┆ Number ┆   ┆ ---       ┆ ---    ┆ ---         ┆ ---   │
│ str        ┆ str          ┆ ---          ┆ ---    ┆   ┆ str       ┆ str    ┆ str         ┆ str   │
│            ┆              ┆ date         ┆ str    ┆   ┆           ┆        ┆             ┆       │
╞════════════╪══════════════╪══════════════╪════════╪═══╪═══════════╪════════╪═════════════╪═══════╡
│ 2022_06    ┆ UO - JDSU    ┆ null         ┆ null   ┆ … ┆ No        ┆ No     ┆ null        ┆ null  │
│            ┆ (June        ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│            ┆ 2022).pdf    ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│ 2022_09    ┆ UO - JDSU    ┆ 2022-09-21   ┆ null   ┆ … ┆ No        ┆ No     ┆ null        ┆ null  │
│            ┆ (September   ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│            ┆ 2022).pdf    ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│ 2022_07    ┆ UO - JDSU    ┆ null         ┆ null   ┆ … ┆ No        ┆ No     ┆ null        ┆ null  │
│            ┆ (July        ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│            ┆ 2022).pdf    ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│ 2022_07    ┆ UO - JDSU    ┆ null         ┆ null   ┆ … ┆ No        ┆ No     ┆ null        ┆ null  │
│            ┆ (July        ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│            ┆ 2022).pdf    ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
│ 2021_01    ┆ Duff, Brian  ┆ 2021-02-03   ┆ null   ┆ … ┆ No        ┆ No     ┆ null        ┆ null  │
│            ┆ 1-21.pdf     ┆              ┆        ┆   ┆           ┆        ┆             ┆       │
└────────────┴──────────────┴──────────────┴────────┴───┴───────────┴────────┴─────────────┴───────┘

In [10]:
#And all the database:
root = Path('..')
parquet_path = root / 'data/jails-data/output/jails_pdfs.parquet'
df = pl.read_parquet(parquet_path)
list(df['Facility Name'][0:10])

['‘acility Name: Williamson County Jail\n',
 "‘acility Name: Kane County Sheriff's Office\n",
 '‘acility Name: /¥lATTHSOns = otice = bn FAPAMEAT\nTT eee Py ml a ei fF gt Mm Ahh sn\n',
 '-acility Name: McHenry County Adult Correctional Facility\n',
 'Fax: (217) 558-4004\n‘acility Name: \\ tei So ( ae ( She cA Ofce\n',
 '-acility Name: Lake County Adult Corrections\n',
 '-acility Name: Lake County Jail\n',
 'Facility Name: Lake County Jail\n',
 'Fax: (217) 522-3906\n-acility Name: McLean County Jail\n',
 '‘acility Name: Macoupin County Sheriff\n']

In [16]:
def clean_facility_name(df):
    """Clean facility names using Polars expressions"""
    return df.with_columns(
        pl.col('Facility Name')
        # First, clean OCR artifacts
        .str.replace_all(r'\\n|\\\\|\\/', ' ')  # Remove \n, \\, \/
        .str.replace_all(r'\n', ' ')  # Remove actual newlines
        .str.replace_all(r'[\\\/]+', ' ')  # Clean slashes
        .str.replace_all(r'\s+', ' ')  # Multiple spaces to single
        .str.strip_chars()  # Trim whitespace
        # Extract facility name after any variation of "Name:"
        .str.extract(r'cility Name:\s*(.+)', 1)
        # Additional cleanup of extracted names
        .str.replace_all(r'[^a-zA-Z\s\'-]', ' ')  # Keep only letters, spaces, apostrophes, hyphens
        .str.replace_all(r'\s+', ' ')  # Clean multiple spaces again
        .str.strip_chars()  # Final trim
        .alias('Cleaned Facility Name')
    )

# Apply the cleaning
df_cleaned = clean_facility_name(df)
df_cleaned['Facility Name', 'Cleaned Facility Name']

shape: (25_613, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ Facility Name                   ┆ Cleaned Facility Name           │
│ ---                             ┆ ---                             │
│ str                             ┆ str                             │
╞═════════════════════════════════╪═════════════════════════════════╡
│ ‘acility Name: Williamson Coun… ┆ Williamson County Jail          │
│ ‘acility Name: Kane County She… ┆ Kane County Sheriff's Office    │
│ ‘acility Name: /¥lATTHSOns = o… ┆ lATTHSOns otice bn FAPAMEAT TT… │
│ -acility Name: McHenry County … ┆ McHenry County Adult Correctio… │
│ Fax: (217) 558-4004             ┆ tei So ae She cA Ofce           │
│ ‘acility N…                     ┆                                 │
│ …                               ┆ …                               │
│ Facility Name: FF RB i EN BE N… ┆ FF RB i EN BE NEN FEE he Rie h… │
│ SANs (att) Vee VI ——es-         ┆ null                            │
│ ‘acili…                         ┆                                 │
│ Facility Name: Lake County She… ┆ Lake County Sheriff's Office    │
│ -acility Name: Lake County Jai… ┆ Lake County Jail                │
│ SANs (att) Vee VI ——es-         ┆ null                            │
│ ‘acili…                         ┆                                 │
└─────────────────────────────────┴─────────────────────────────────┘

In [22]:
#Cleanning the date
list(df_cleaned['Date'][:10])

['Date of Occurrence: 01/14/2021\n',
 'Date of Occurrence: 01/27/2021\n',
 'Date of Occurrence: i/ (Z]2 ( Tir\n',
 'Date of Occurrence: 01/09/2021\n',
 'aAqaaress. eet o~ SF Never\nPate af Praacemmamane f—) 7 + ed } fs 9 ng\n',
 'Date of Occurrence: 01/15/2021\n',
 'Date of Occurrence: 01/19/2021\n',
 'Date of Occurrence: 01/13/2021\n',
 'AGaress. 14 West STORE SUCCL\nStreet\nRiwten af Manairrramnna: (111/12£/9N%1 ~\n',
 'Date of Occurrence: 01/26/2021 T\n']

In [ ]:
def clean_date_occurrence(df):
    """Clean date of occurrence using Polars expressions"""
    return df.with_columns(
        pl.col('Date')
        # First, clean OCR artifacts
        .str.replace_all(r'\\n|\\\\|\\/', ' ')  # Remove \n, \\, \/
        .str.replace_all(r'\n', ' ')  # Remove actual newlines
        .str.replace_all(r'[\\\/]+', ' ')  # Clean slashes
        .str.replace_all(r'\s+', ' ')  # Multiple spaces to single
        .str.strip_chars()  # Trim whitespace
        # Extract date after "Date of Occurrence:"
        .str.extract(r'Date of Occurrence:\s*([0-9]{1,2}/[0-9]{1,2}/[0-9]{4})', 1)
        .alias('Cleaned Date')
    )

# Apply the cleaning
df_cleaned = clean_date_occurrence(df_cleaned)
df_cleaned.select(['Date', 'Cleaned Date']).head(10)

shape: (10, 2)
┌─────────────────────────────────┬──────────────┐
│ Date                            ┆ Cleaned Date │
│ ---                             ┆ ---          │
│ str                             ┆ str          │
╞═════════════════════════════════╪══════════════╡
│ Date of Occurrence: 01/14/2021… ┆ null         │
│ Date of Occurrence: 01/27/2021… ┆ null         │
│ Date of Occurrence: i/ (Z]2 ( … ┆ null         │
│ Date of Occurrence: 01/09/2021… ┆ null         │
│ aAqaaress. eet o~ SF Never      ┆ null         │
│ Pat…                            ┆              │
│ Date of Occurrence: 01/15/2021… ┆ null         │
│ Date of Occurrence: 01/19/2021… ┆ null         │
│ Date of Occurrence: 01/13/2021… ┆ null         │
│ AGaress. 14 West STORE SUCCL    ┆ null         │
│ S…                              ┆              │
│ Date of Occurrence: 01/26/2021… ┆ null         │
└─────────────────────────────────┴──────────────┘